import { z } from "zod";
import { FactId, HexColor, LocaleTag } from "./ids.ts";

/**
 * ProductSource — the ground truth about a product, as ingested from a merchant feed, a catalog dataset, the DB
 * or a JSON file. Every sales claim in a reel must trace to a fact here (ClaimValidator). Nothing in this object
 * is generated by a model.
 */

export const FactKind = z.enum([
  "dimension",
  "weight",
  "material",
  "color",
  "power",
  "capacity",
  "performance",
  "feature",
  "included",
  "warranty",
  "certificate",
  "price",
  "promotion",
  "usage",
  "assembly",
  "other",
]);
export type FactKind = z.infer<typeof FactKind>;

export const ProductFact = z.object({
  id: FactId,
  kind: FactKind,
  /** the fact in the source language, as written by the source */
  text: z.string().min(1).max(600),
  /** numeric value + unit when the fact is quantitative (used to verify numbers in copy) */
  value: z.number().optional(),
  unit: z.string().max(24).optional(),
  /** where it comes from: field name / URL / document */
  source: z.string().max(300),
  locale: LocaleTag.default("en-US"),
  /** ISO date the source was read (prices and promotions go stale) */
  asOf: z.string().optional(),
});
export type ProductFact = z.infer<typeof ProductFact>;

export const ProductImage = z.object({
  /** local file path (downloaded / cached) */
  path: z.string(),
  url: z.string().optional(),
  role: z.enum(["main", "detail", "lifestyle", "packaging", "other"]).default("other"),
  width: z.number().int().positive().optional(),
  height: z.number().int().positive().optional(),
  license: z.string(),
});
export type ProductImage = z.infer<typeof ProductImage>;

export const ProductModel3D = z.object({
  path: z.string(),
  format: z.enum(["glb", "gltf", "obj", "fbx", "usd", "blend"]),
  /** real-world size of the model's largest extent in metres (from the source) when known */
  extentM: z.object({ x: z.number(), y: z.number(), z: z.number() }).optional(),
  license: z.string(),
  /** sha256 of the file — part of every render cache key */
  sha256: z.string().optional(),
});
export type ProductModel3D = z.infer<typeof ProductModel3D>;

export const ProductPrice = z.object({
  amount: z.number().nonnegative(),
  currency: z.string().length(3),
  asOf: z.string(),
  source: z.string(),
  factId: FactId,
});

export const ProductSource = z.object({
  id: z.string().min(1).max(120),
  source: z.object({
    kind: z.enum(["abo", "json", "db", "feed", "url"]),
    ref: z.string().max(500),
    license: z.string().max(200),
    attribution: z.string().max(500).optional(),
  }),
  brand: z.string().max(120),
  /** localized product names as published by the source */
  names: z.record(LocaleTag, z.string().min(1).max(300)),
  category: z.string().max(120),
  categoryPath: z.string().max(300).optional(),
  modelNumber: z.string().max(80).optional(),
  /** the offered colour variant (accuracy check compares rendered colour against it) */
  color: z.object({ name: z.string(), hex: HexColor.optional() }).optional(),
  price: ProductPrice.optional(),
  facts: z.array(ProductFact).max(200),
  images: z.array(ProductImage).max(40),
  model3d: ProductModel3D.optional(),
  /** where a customer would buy it (affiliate link resolved elsewhere) */
  offerUrl: z.string().optional(),
});
export type ProductSource = z.infer<typeof ProductSource>;

/** A selling point / feature linked to the facts that prove it. */
export const LinkedPoint = z.object({
  text: z.string().min(1).max(200),
  factIds: z.array(FactId).min(1).max(6),
});
export type LinkedPoint = z.infer<typeof LinkedPoint>;

/**
 * ProductProfile — the analysed, reel-ready view of a product (Gemini multimodal analysis, or the deterministic
 * extractor). Cached by source hash: a product is analysed once, not per reel.
 */
export const ProductProfile = z.object({
  productId: z.string(),
  sourceHash: z.string(),
  category: z.string().max(80),
  /** short name for on-screen use, per locale when known */
  shortName: z.string().max(60),
  visual_features: z.array(z.string().max(80)).max(12),
  selling_points: z.array(LinkedPoint).max(10),
  technical_features: z.array(LinkedPoint).max(12),
  likely_customer: z.array(z.string().max(100)).max(6),
  /** what the studio can show well (e.g. "warm glow through the fabric shade", "walnut grain macro") */
  visual_opportunities: z.array(z.string().max(120)).max(8),
  /** claims to avoid / accuracy risks (e.g. "do not imply dimmable — not in source") */
  risks: z.array(z.string().max(160)).max(10),
  /** expected dominant colours of the real product (accuracy check) */
  palette: z.array(HexColor).max(6),
  /** the product emits light / has a moving part / has a screen — drives shot choice */
  traits: z.object({
    emitsLight: z.boolean(),
    hasMovingParts: z.boolean(),
    hasScreen: z.boolean(),
    tall: z.boolean(),
  }),
  analyzer: z.object({ provider: z.string(), model: z.string(), version: z.string() }),
});
export type ProductProfile = z.infer<typeof ProductProfile>;
