import type { ModelClass } from "./providers.ts";

/**
 * Generation tiers (see docs/COST_MODEL.md). The MediaGenerationRouter picks one per content item;
 * these plans define what each tier is allowed to spend money on.
 */
export type TierKey = "TIER_0" | "TIER_1" | "TIER_2" | "TIER_3";

export interface TierPlan {
  tier: TierKey;
  label: string;
  description: string;
  imageClass: ModelClass;
  /** Max number of AI-generated stills (backgrounds/scenes). Real product images are always free to use. */
  maxGeneratedImages: number;
  aiVideoShots: number;
  aiVideoSecondsPerShot: number;
  videoClass: ModelClass | null;
  /** Whether a voice-over is generated by default (brands can override). */
  voiceoverDefault: boolean;
  backgroundRemoval: boolean;
}

export const TIER_PLANS: Record<TierKey, TierPlan> = {
  TIER_0: {
    tier: "TIER_0",
    label: "Tier 0 — cheap test",
    description:
      "Real product images, up to 2 cheap generated backgrounds, programmatic motion (zoom/pan/parallax), kinetic typography.",
    imageClass: "cheap",
    maxGeneratedImages: 2,
    aiVideoShots: 0,
    aiVideoSecondsPerShot: 0,
    videoClass: null,
    voiceoverDefault: false,
    backgroundRemoval: true,
  },
  TIER_1: {
    tier: "TIER_1",
    label: "Tier 1 — one AI shot",
    description: "Tier 0 plus one 5 s image-to-video shot with a low-cost model.",
    imageClass: "cheap",
    maxGeneratedImages: 3,
    aiVideoShots: 1,
    aiVideoSecondsPerShot: 5,
    videoClass: "cheap",
    voiceoverDefault: true,
    backgroundRemoval: true,
  },
  TIER_2: {
    tier: "TIER_2",
    label: "Tier 2 — higher quality",
    description:
      "Better image model and a higher-quality image-to-video shot for commercially valuable content.",
    imageClass: "standard",
    maxGeneratedImages: 4,
    aiVideoShots: 1,
    aiVideoSecondsPerShot: 5,
    videoClass: "standard",
    voiceoverDefault: true,
    backgroundRemoval: true,
  },
  TIER_3: {
    tier: "TIER_3",
    label: "Tier 3 — proven winner",
    description: "Premium models and multiple AI video shots. Only for ideas/products with proven analytics.",
    imageClass: "premium",
    maxGeneratedImages: 5,
    aiVideoShots: 3,
    aiVideoSecondsPerShot: 5,
    videoClass: "premium",
    voiceoverDefault: true,
    backgroundRemoval: true,
  },
};

export const TIER_ORDER: TierKey[] = ["TIER_0", "TIER_1", "TIER_2", "TIER_3"];

export function tierIndex(tier: TierKey): number {
  return TIER_ORDER.indexOf(tier);
}
